apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: ghcr.io/kagent-dev/kagent/helm
    chart: kagent
    targetRevision: 0.8.3
    helm:
      parameters:
        - name: providers.default
          value: ollama
        - name: providers.ollama.config.host
          value: ollama.agentgateway-system.svc.cluster.local:11434
        - name: providers.ollama.model
          value: gemma4:26b
        - name: ui.service.type
          value: LoadBalancer
        - name: ui.service.ports.port
          value: "80"
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
