apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway-ollama
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/k0rvih/course-aire
    targetRevision: main
    path: argocd/templates/ollama
    directory:
      recurse: true
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: agentgateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
